---
resources:
  - name: mytutorial
    type: git
    source:
      uri: https://github.com/yejhinfo/concourse-test.git
      branch: main
      
jobs:
  - name: test
    public: true
    serial: true
    plan:
      - get: tutorial
        trigger: true
      - get: mytutorial
        trigger: true
      - task: test-sometimes-works
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
            - name: mytutorial
          run:
            path: mytutorial/test.sh